### ISSUE TITLE
New node containers retry registration but fail until distributor is restarted

### ISSUE THREAD

**Issue by nextrevision** [SeleniumHQ/docker-selenium#1337]
## 🐛 Bug Report

When deployed on kubernetes with distributed components (router, event bus, etc), new nodes seldom get registered until distributor is restarted (container killed and recreated). The distributor error below only gets logged once, not multiple times which makes it seem like the node keeps emitting registration events, but the distributor tries once and not again.

Distributor error:
```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.12.136.44:5555
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Chrome node:

```
2021-07-15 23:39:29,454 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2021-07-15 23:39:29,456 INFO supervisord started with pid 9
2021-07-15 23:39:30,459 INFO spawned: 'xvfb' with pid 11
2021-07-15 23:39:30,461 INFO spawned: 'vnc' with pid 12
2021-07-15 23:39:30,463 INFO spawned: 'novnc' with pid 13
2021-07-15 23:39:30,475 INFO spawned: 'selenium-node' with pid 14
2021-07-15 23:39:30,555 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-07-15 23:39:30,555 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-07-15 23:39:30,555 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-07-15 23:39:30,555 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Appending Selenium options: --register-cycle 30 --register-period 300
Configuring server...
Setting up SE_NODE_HOST...
Setting up SE_NODE_PORT...
Setting up SE_NODE_GRID_URL...
Selenium Grid Node configuration: 
[events]
publish = "tcp://selenium-event-bus:4442"
subscribe = "tcp://selenium-event-bus:4443"

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "91.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Node...
23:39:31.848 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
23:39:31.853 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
23:39:32.067 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-event-bus:4442 and tcp://selenium-event-bus:4443
23:39:32.250 INFO [UnboundZmqEventBus.<init>] - Sockets created
23:39:33.279 INFO [UnboundZmqEventBus.<init>] - Event bus ready
23:39:33.525 INFO [NodeServer.createHandlers] - Reporting self as: http://10.12.136.44:5555
23:39:33.581 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
23:39:33.676 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "91.0","browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 1 times
23:39:33.687 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
23:39:34.154 INFO [NodeServer$1.start] - Starting registration process for node id 2531c040-42c5-47a6-a291-ad5e154e3d7b
23:39:34.159 INFO [NodeServer.execute] - Started Selenium node 4.0.0-rc-1 (revision 74745cf081): http://10.12.136.44:5555
23:39:34.171 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:40:04.178 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:40:34.180 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:41:04.182 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:41:34.184 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:42:04.187 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:42:34.188 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:43:04.190 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
23:43:34.191 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

I was testing trying different combinations of timeouts with `--register-cycle 30 --register-period 300`, but the issue is the same. I first noticed this issue, however, using the default node container settings.

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

* Deploy
```
kubectl create ns selenium-grid
kubectl apply -n selenium-grid -f https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/trunk/k8s-deployment-full-grid.yaml
kubectl rollout status --watch -n selenium-grid deployment/selenium-chrome-node-deployment
kubectl rollout status --watch -n selenium-grid deployment/selenium-distributor-deployment
```

* Scale chrome nodes
```
kubectl scale --replicas=3 -n selenium-grid deployment/selenium-chrome-node-deployment
kubectl rollout status --watch -n selenium-grid deployment/selenium-chrome-node-deployment
```

* Check distributor logs for `Connection Refused` error.
```
kubectl logs -n selenium-grid deployment/selenium-distributor-deployment
```

* Restart (delete) distributor container and watch nodes register.
```
kubectl rollout restart -n selenium-grid deployment/selenium-distributor-deployment
kubectl rollout status --watch -n selenium-grid deployment/selenium-distributor-deployment
kubectl logs -n selenium-grid deployment/selenium-distributor-deployment -f
```

## Expected behavior

Nodes are retried by distributor.

## Test script reproducing this issue (when applicable)

See "To Reproduce".

## Environment

OS: k8s (EKS)
Docker-Selenium image version: 4.0.0-rc-1-prerelease-20210713 
Docker version: k8s v1.18
Exact Docker command to start the containers: see https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/trunk/k8s-deployment-full-grid.yaml

**Comment by IanDT** [comment]
This may well be the same problem as reported in https://github.com/SeleniumHQ/docker-selenium/issues/1270.

I've added a comment to that issue noting that restarting the hub also results in all nodes connecting to the hub successfully, as does starting up all the nodes before starting the hub.

**Comment by nextrevision** [comment]
That's precisely it. If running in a distributed setup, the distributor needs to be restarted but if running in an all-in-one, then it's the hub. I have suspected that there is a race condition between the time the Kubernetes readiness check passes and the corresponding iptables/entries/etc rules are propagated throughout the system. So the node sends the first registration event and the distributor immediately begins checking and receiving a connection refused error. There are some flaws in that theory and I think it's sort of irrelevant anyways.

I would expect the subsequent node emitted registration events to cause the distributor to retry the connection/registration, in which case I would expect the node to eventually register. From what I've noticed, the distributor tries once, throws the connection exception, then doesn't try again.

**Comment by assilzm** [comment]
Have the same problem with version 4.0.0-rc-1-prerelease-20210713.But it works fine with version 3.

**Comment by komby** [comment]
Also experiencing this issue using 4.0.0-rc-1-prerelease-20210713.  After deploying fresh the kubectl rollout restart -n selenium-grid deployment/selenium-distributor-deployment command is needed for nodes to register.

**Comment by diemol** [comment]
Could someone please provide the full distributor logs? Not just a snippet of it.

**Comment by nextrevision** [comment]
@diemol Sure thing, here's the full output of the distributor following the steps to reproduce above:

```
2021-08-06 19:25:50,402 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-distributor.conf" during parsing
2021-08-06 19:25:50,404 INFO supervisord started with pid 9
2021-08-06 19:25:51,407 INFO spawned: 'selenium-grid-distributor' with pid 11
Starting Selenium Grid Distributor...
2021-08-06 19:25:51,415 INFO success: selenium-grid-distributor entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
19:25:52.365 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
19:25:52.394 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
19:25:52.695 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-event-bus:4442 and tcp://selenium-event-bus:4443
19:25:52.850 INFO [UnboundZmqEventBus.<init>] - Sockets created
19:25:53.857 INFO [UnboundZmqEventBus.<init>] - Event bus ready
19:25:54.971 INFO [DistributorServer.execute] - Started Selenium Distributor 4.0.0-rc-1 (revision c498dad8c5): http://10.1.1.82:5553
19:27:14.958 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
19:27:16.016 INFO [LocalDistributor.add] - Added node 61f241c7-6941-47db-bdf9-6777904ae296 at http://10.1.1.85:5555. Health check every 120s
19:27:16.076 INFO [GridModel.setAvailability] - Switching node 61f241c7-6941-47db-bdf9-6777904ae296 (uri: http://10.1.1.85:5555) from DOWN to UP
19:30:46.163 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
19:30:46.220 WARN [UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2] - Caught exception from listener: org.openqa.selenium.events.EventListener@18c5f282
java.io.UncheckedIOException: java.net.ConnectException: Connection refused: /10.1.1.88:5555
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:80)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:116)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.grid.node.remote.RemoteNode.getStatus(RemoteNode.java:207)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.add(LocalDistributor.java:254)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.register(LocalDistributor.java:243)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.lambda$new$1(LocalDistributor.java:167)
	at org.openqa.selenium.events.EventListener.accept(EventListener.java:43)
	at org.openqa.selenium.events.EventListener.accept(EventListener.java:25)
	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2(UnboundZmqEventBus.java:273)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused: /10.1.1.88:5555
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.1.1.88:5555
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by karthikeayan** [comment]
Running into same issue, I am trying to add 30+ container chrome nodes into the hub. I see only 1 or 2 getting registered with hub.

**Comment by Chainfire** [comment]
Having the same issue on GKE, restarting distributor/hub every time I add a node seems to be the only thing that works. Nodes have to be up before the distributor or it doesn't get registered... Logs posted here are the same as mine, nothing more interesting to see from mine.

**Comment by rgarabedian** [comment]
I've been testing with Grid4 over the past several weeks and I'm seeing the same thing, albeit the errors are sporadic. 

My setup is hosted in Azure. We have one container instance for the hub, and two container instances for nodes. The node container instances contain four node containers (selenium/node-chrome:4.0.0-rc-1-prerelease-20210713) that run a single browser each. In total, we are execute tests against 8 chrome browsers.

The azure containers are started with the hub first, followed by the two nodes.

```
az container start --name hub_container --resource-group Selenium
az container start --name node_container_1 --resource-group Selenium
az container start --name node_container_2 --resource-group Selenium
```

In the few instances I've seen this issue, one of the nodes fails to connect. The status endpoint (/wd/hub/status) shows the grid is ready, but the reported node count lists 7 nodes, instead of 8.

**Hub log when the issue happens:**

```
2021-08-13 16:03:02,892 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2021-08-13 16:03:02,899 INFO supervisord started with pid 17
2021-08-13 16:03:03,901 INFO spawned: 'selenium-grid-hub' with pid 27
2021-08-13 16:03:04,904 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
16:03:05.159 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:03:05.179 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:03:05.439 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://127.0.0.1:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://127.0.0.1:4443]
16:03:05.635 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://127.0.0.1:4442 and tcp://127.0.0.1:4443
16:03:05.710 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:03:06.717 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:03:08.621 INFO [Hub.execute] - Started Selenium Hub 4.0.0-rc-1 (revision 74745cf081): http://192.168.0.47:4444
16:04:53.463 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
16:04:57.702 INFO [LocalDistributor.add] - Added node 51cc5466-833c-4bdb-844e-259f5ce3ef87 at http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5555. Health check every 120s
16:04:57.756 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
16:04:57.867 INFO [LocalDistributor.add] - Added node 6f865387-b2a1-4768-b4a3-b0b0b53b92b1 at http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5556. Health check every 120s
16:04:57.873 INFO [GridModel.setAvailability] - Switching node 51cc5466-833c-4bdb-844e-259f5ce3ef87 (uri: http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5555) from DOWN to UP
16:04:57.875 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
16:04:59.086 INFO [LocalDistributor.add] - Added node 76e40115-6901-44a9-9ebc-eaf7b791f43c at http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5557. Health check every 120s
16:04:59.090 INFO [GridModel.setAvailability] - Switching node 6f865387-b2a1-4768-b4a3-b0b0b53b92b1 (uri: http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5556) from DOWN to UP
16:04:59.093 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
16:05:00.267 INFO [LocalDistributor.add] - Added node 1a7b8988-7222-4992-9e1f-ca52fcda55f0 at http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5558. Health check every 120s
16:05:00.278 INFO [GridModel.setAvailability] - Switching node 76e40115-6901-44a9-9ebc-eaf7b791f43c (uri: http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5557) from DOWN to UP
16:05:00.293 INFO [GridModel.setAvailability] - Switching node 1a7b8988-7222-4992-9e1f-ca52fcda55f0 (uri: http://XXXXXXXXXXXX.eastus2.azurecontainer.io:5558) from DOWN to UP
16:06:20.727 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
16:06:30.770 WARN [UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2] - Caught exception from listener: org.openqa.selenium.events.EventListener@b0005ae
java.io.UncheckedIOException: java.net.ConnectException: connection timed out: YYYYYYYYYYYYYY.eastus2.azurecontainer.io/20.190.204.142:5555
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:80)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:116)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.grid.node.remote.RemoteNode.getStatus(RemoteNode.java:207)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.add(LocalDistributor.java:254)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.register(LocalDistributor.java:243)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.lambda$new$1(LocalDistributor.java:167)
	at org.openqa.selenium.events.EventListener.accept(EventListener.java:43)
	at org.openqa.selenium.events.EventListener.accept(EventListener.java:25)
	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2(UnboundZmqEventBus.java:273)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: connection timed out: YYYYYYYYYYYYYY.eastus2.azurecontainer.io/20.190.204.142:5555
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: YYYYYYYYYYYYYY.eastus2.azurecontainer.io/20.190.204.142:5555
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	... 9 more
16:06:30.773 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
16:06:30.886 INFO [LocalDistributor.add] - Added node 4be83022-4014-4478-b787-af4a5f01312e at http://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:5556. Health check every 120s
16:06:30.890 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
16:06:30.982 INFO [LocalDistributor.add] - Added node 3bd851e7-a810-45b0-ba82-29defb4a3bed at http://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:5557. Health check every 120s
16:06:30.985 INFO [GridModel.setAvailability] - Switching node 4be83022-4014-4478-b787-af4a5f01312e (uri: http://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:5556) from DOWN to UP
```

**Log from the node that can't connect**


```
2021-08-13 16:06:15,817 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2021-08-13 16:06:15,819 INFO supervisord started with pid 9
2021-08-13 16:06:16,821 INFO spawned: 'xvfb' with pid 11
2021-08-13 16:06:16,824 INFO spawned: 'vnc' with pid 12
2021-08-13 16:06:16,827 INFO spawned: 'novnc' with pid 13
2021-08-13 16:06:16,829 INFO spawned: 'selenium-node' with pid 14
2021-08-13 16:06:16,877 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-08-13 16:06:16,877 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-08-13 16:06:16,877 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-08-13 16:06:16,877 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Selenium Grid Node configuration: 
[events]
publish = "tcp://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:4442"
subscribe = "tcp://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:4443"

[server]
host = "YYYYYYYYYYYYYY.eastus2.azurecontainer.io"
port = "5555"
[node]
grid-url = "YYYYYYYYYYYYYY.eastus2.azurecontainer.io:4444"
session-timeout = "600"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "91.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Node...
16:06:18.278 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:06:18.286 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:06:18.597 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:4442 and tcp://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:4443
16:06:18.798 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:06:19.805 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:06:20.195 INFO [NodeServer.createHandlers] - Reporting self as: http://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:5555
16:06:20.272 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
16:06:20.383 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "91.0","browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 1 times
16:06:20.394 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
16:06:21.112 INFO [NodeServer$1.start] - Starting registration process for node id 02f0db27-4fbe-4d49-9975-202058117e5f
16:06:21.114 INFO [NodeServer.execute] - Started Selenium node 4.0.0-rc-1 (revision 74745cf081): http://YYYYYYYYYYYYYY.eastus2.azurecontainer.io:5555
16:06:21.124 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:06:31.130 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:06:41.134 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:06:51.136 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:07:01.138 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:07:11.140 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:07:21.142 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:07:31.145 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:07:41.147 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:07:51.149 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:08:01.151 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:08:11.153 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:08:21.122 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

**Comment by Chainfire** [comment]
Already fixed in HEAD ? @diemol 

I need this up and running yesterday so I decided to go take a look at building from source. As a first test, I just built from HEAD and pushed that jar to my hub instance to see if the build even runs, and surprisingly (as I didn't modify any code) the registration issue disappears.

Built from: https://github.com/SeleniumHQ/selenium/commit/72ffec9d2a241bd7833415f1b7b29499fff5c2c4

Build commands:
```
bazel build java/...
bazel build grid
```

Output used: `bazel-bin/java/src/org/openqa/selenium/grid/selenium`
Download (temporary): [selenium-server-72ffec9d.jar](https://jongma.org/tmp/selenium/selenium-server-72ffec9d.jar)

YAML modification (note *command*) for hub:
```
      containers:
        - name: selenium-hub
          image: selenium/hub:4.0.0-rc-1-prerelease-20210804
          command: ['sh', '-c', "sudo wget https://jongma.org/tmp/selenium/selenium-server-72ffec9d.jar -O /opt/selenium/selenium-server.jar && /opt/bin/entry_point.sh"]
```
Other containers were *not* modified, just the hub.

Haven't tested with a distributor instead of hub, but in hub mode it successfully registered all new nodes created with `kubectl scale` immediately. If I manually delete node pods so GKE restarts them, they get added back immediately as well, without restarting the hub. No timeout exceptions in the log anymore.

Anyone here is welcome to *test* the JAR linked above but obviously don't rely on that link for production.

**Comment by j3soon** [comment]
## To Reproduce

The similar issue can be reproduced in Docker:

```sh
mkdir tmp && cd tmp
wget https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/a88edbe3422cd0017fa50bc707664b4556cba001/docker-compose-v3.yml

docker-compose -f docker-compose-v3.yml up
# wait for the containers to launch
docker restart tmp_chrome_1
# chrome node is missing in localhost:4444/
docker-compose -f docker-compose-v3.yml down
docker rm -f $(docker ps -a -q)
cd .. && rm -r tmp
```

## Quick Fix

Use `4.0.0-rc-1-prerelease-20210618` instead of `4.0.0-rc-1-prerelease-20210804`.

```sh
mkdir tmp && cd tmp
wget https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/a88edbe3422cd0017fa50bc707664b4556cba001/docker-compose-v3.yml

# Use 4.0.0-rc-1-prerelease-20210618 instead
sed -i 's/20210804/20210618/g' docker-compose-v3.yml

docker-compose -f docker-compose-v3.yml up
# wait for the containers to launch
docker restart tmp_chrome_1
# chrome node is visible in localhost:4444/
docker-compose -f docker-compose-v3.yml down
docker rm -f $(docker ps -a -q)
cd .. && rm -r tmp
```

## Further Details

This issue persists in:
- `4.0.0-rc-1-prerelease-20210804`
- `4.0.0-rc-1-prerelease-20210713`

But works well in:
- `4.0.0-rc-1-prerelease-20210618`

The issue seems to reside on the `selenium/node-*` side instead of the `selenium/hub` side.

(I believe this issue is related to issues: #1270 and #1364)

**Comment by diemol** [comment]
We've [fixed this](https://github.com/SeleniumHQ/selenium/commit/a4c3e3b8fb78541ecc7676bb76aa4608e5c1c9ee) and we just made a new [prerelease](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210823).

**Comment by j3soon** [comment]
Thanks @diemol! I just used the `4.0.0-rc-1-prerelease-20210823` image and confirmed that the issue is fixed.

**Comment by nextrevision** [comment]
Also can confirm it is working now. Thanks!!!

**Comment by gtaujeky** [comment]
Hi there,

I'm still having this issue (it's quite random) using the latest version `4.0.0-rc-2-prerelease-20210916`

I'm running in distributed mode on GKE with the yaml provided
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml

The issue seems to be only happening when I'm scaling up the number of selenium-chrome-node (while everything else is already running).

It's quite random, but sometimes it takes up to 2-3 min to have the node to be marked as UP.

e.g logs from distributor

```
05:48:41.164 INFO [LocalDistributor.add] - Added node 4e14586b-fc8f-49fd-9b4c-03567e20a250 at http://172.24.11.38:5555. Health check every 120s

05:51:29.984 INFO [GridModel.setAvailability] - Switching node 4e14586b-fc8f-49fd-9b4c-03567e20a250 (uri: http://172.24.11.38:5555) from DOWN to UP
```
